### ISSUE TITLE
Having trouble compiling on Windows 10

### ISSUE THREAD

**Issue by ArgentumBlack** [TatsuyaShirakawa/poincare-embedding#2]
Hi, I was trying to work on this project. But I had some trouble trying to compile it. I got 'Cmake' work successfully, but it seemed the 'Make' command only works on Linux, not Windows. I also tried to use Visual Studio 2017 which automatically detects the CMakeList file and try to compile the project, but it also failed.  Is there any chance that you might have some advice for me on how to make your code work on Windows? Would really appreciate it!

**Comment by TatsuyaShirakawa** [comment]
@ArgentumBlack Hi, thank you for trying my codes and reporting this issue.
How about commenting out the following lines from CMakeLists.txt? I suspect it's a pthread issue.
```
# pthread
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
target_link_libraries(poincare_embedding Threads::Threads)
```

**Comment by ArgentumBlack** [comment]
@TatsuyaShirakawa Thanks for replying！ Unfortunately，after commenting those lines, VisualStudio still fail to work. I ended up building a Linux Virtual machine and ran your code on it. Still, thanks a lot and your code has been very helpful!

**Comment by PredM** [comment]
Maybe it could be interessting for other people with a Win10 environment: you can compile it with cygwin (cmake and gcc-g++ must be selected during cygwin installation). That worked for me, thanks for the code!

**Comment by TatsuyaShirakawa** [comment]
@patrickgitacc Thanks for your nice suggestion! I added your recommendation in README.md :)
