### ISSUE TITLE
about the derivative calculation

### ISSUE THREAD

**Issue by ppen2013** [TatsuyaShirakawa/poincare-embedding#4]
hello, i found that in the paper the loss function is log(e^-d(uv)/sum(e^-d(u,v'))). 
it seems that the derivative over positive sample d() is -1, and the derivative over negative sample d() is e^d()/Z.
But in this C++ implementation , it seems not like that . 
I was wondering whether i miss something.
looking forward your relpy
thanks

**Comment by TatsuyaShirakawa** [comment]
the variable u appears in both numerator and denominator, so the derivative is a little bit more complicated. I can help you if you write more concretely about your issues (with more concrete expressions)  :)

**Comment by ppen2013** [comment]
thanks for reply.
I scan the paper again about the loss function definition. 
I seems that in the denominator we have the element e^-d(u,u) but not e^-d(u,v), I am not sure if I misunderstand it. The paper wrote that v'∈N(u), N(u)={v|(u,v)∉D} ∪{u}

**Comment by ppen2013** [comment]
Finally, I found the newest version of the paper from nips and the loss function interpretation was different from the one I saw before. 
thank you all the same
