### ISSUE TITLE
Verification of results

### ISSUE THREAD

**Issue by navidre** [TatsuyaShirakawa/poincare-embedding#5]
Thank you for the code.

It will be good to verify the resulting embeddings further, especially reproducing Table 1 of paper:

![table1](https://user-images.githubusercontent.com/1976093/33596418-d840bda4-d958-11e7-8eb3-85dbca4d3a61.png)

**Comment by TatsuyaShirakawa** [comment]
Thank you for the suggestion!
Acturally doing something complicated in C++ is a little troublesome :(, so I've written poincare embeddings in pytorch  some month ago, but the version of pytorch (v0.2) at that time had some crucial issues in nn.Embeddings and sparse optimizers. 
Currently pytorch v0.3 was released and the issues seems to be fixed, so I'll try rewriting poincare embedding in pytorch of v0.3. If it goes well, I'll release the code.
